console.log("Hello world");
let name = "Mario";
let age = 22;
let isfemale = true;
let clg = "suk";
let goals = "clear&firm";
console.log(name);
console.log(age);
console.log(isfemale);
console.log(clg);
console.log(goals);